2025-09-23 20:18:44 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\api_platform\api_auto\views.py:194" - run_all_cases - INFO - 开始全量执行用例
2025-09-23 20:18:44 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\test_runner\run_case.py:130" - run - INFO - ============================================================
2025-09-23 20:18:44 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\test_runner\run_case.py:131" - run - INFO - 开始接口自动化测试流程
2025-09-23 20:18:44 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\test_runner\run_case.py:132" - run - INFO - 测试环境: test_env
2025-09-23 20:18:44 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\test_runner\run_case.py:133" - run - INFO - ============================================================
2025-09-23 20:18:44 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\test_runner\run_case.py:51" - get_test_suite - INFO - 开始收集测试用例，路径: D:\workdir\DjangoProject3\api_test_platform\api_testcase
2025-09-23 20:18:44 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\test_runner\run_case.py:57" - get_test_suite - INFO - 指定用例ID: None
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:140" - get_merged_info - DEBUG - 工作表 'Sheet1' 合并单元格数量: 0
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:32" - __init__ - INFO - Excel工具初始化完成: test_demo.xls - Sheet1
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:209" - read_multiple_excel_cases - INFO - 发现 4 个Excel文件，开始读取用例...
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:140" - get_merged_info - DEBUG - 工作表 'Sheet1' 合并单元格数量: 10
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:32" - __init__ - INFO - Excel工具初始化完成: 20250923200055_类、方法介绍.xls - Sheet1
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(1,0)属于合并区域，取值(1,0)
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(1,1)属于合并区域，取值(1,0)
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(1,2)属于合并区域，取值(1,0)
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(1,3)属于合并区域，取值(1,0)
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(1,4)属于合并区域，取值(1,0)
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(1,5)属于合并区域，取值(1,0)
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(1,6)属于合并区域，取值(1,0)
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(8,0)属于合并区域，取值(8,0)
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(8,1)属于合并区域，取值(8,0)
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(8,2)属于合并区域，取值(8,0)
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(8,3)属于合并区域，取值(8,0)
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(8,4)属于合并区域，取值(8,0)
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(8,5)属于合并区域，取值(8,0)
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(8,6)属于合并区域，取值(8,0)
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(16,0)属于合并区域，取值(16,0)
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(16,1)属于合并区域，取值(16,0)
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(16,2)属于合并区域，取值(16,0)
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(16,3)属于合并区域，取值(16,0)
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(16,4)属于合并区域，取值(16,0)
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(16,5)属于合并区域，取值(16,0)
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(16,6)属于合并区域，取值(16,0)
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(24,0)属于合并区域，取值(24,0)
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(24,1)属于合并区域，取值(24,0)
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(24,2)属于合并区域，取值(24,0)
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(24,3)属于合并区域，取值(24,0)
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(24,4)属于合并区域，取值(24,0)
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(24,5)属于合并区域，取值(24,0)
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(24,6)属于合并区域，取值(24,0)
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(30,0)属于合并区域，取值(30,0)
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(30,1)属于合并区域，取值(30,0)
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(30,2)属于合并区域，取值(30,0)
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(30,3)属于合并区域，取值(30,0)
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(30,4)属于合并区域，取值(30,0)
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(30,5)属于合并区域，取值(30,0)
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(30,6)属于合并区域，取值(30,0)
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(35,0)属于合并区域，取值(35,0)
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(35,1)属于合并区域，取值(35,0)
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(35,2)属于合并区域，取值(35,0)
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(35,3)属于合并区域，取值(35,0)
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(35,4)属于合并区域，取值(35,0)
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(35,5)属于合并区域，取值(35,0)
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(35,6)属于合并区域，取值(35,0)
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(38,0)属于合并区域，取值(38,0)
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(38,1)属于合并区域，取值(38,0)
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(38,2)属于合并区域，取值(38,0)
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(38,3)属于合并区域，取值(38,0)
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(38,4)属于合并区域，取值(38,0)
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(38,5)属于合并区域，取值(38,0)
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(38,6)属于合并区域，取值(38,0)
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(41,0)属于合并区域，取值(41,0)
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(41,1)属于合并区域，取值(41,0)
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(41,2)属于合并区域，取值(41,0)
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(41,3)属于合并区域，取值(41,0)
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(41,4)属于合并区域，取值(41,0)
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(41,5)属于合并区域，取值(41,0)
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(41,6)属于合并区域，取值(41,0)
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(45,0)属于合并区域，取值(45,0)
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(45,1)属于合并区域，取值(45,0)
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(45,2)属于合并区域，取值(45,0)
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(45,3)属于合并区域，取值(45,0)
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(45,4)属于合并区域，取值(45,0)
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(45,5)属于合并区域，取值(45,0)
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(45,6)属于合并区域，取值(45,0)
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(50,0)属于合并区域，取值(50,0)
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(50,1)属于合并区域，取值(50,0)
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(50,2)属于合并区域，取值(50,0)
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(50,3)属于合并区域，取值(50,0)
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(50,4)属于合并区域，取值(50,0)
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(50,5)属于合并区域，取值(50,0)
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(50,6)属于合并区域，取值(50,0)
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:182" - get_sheet_data_by_dict - INFO - 从工作表 'Sheet1' 读取到 55 条数据
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:221" - read_multiple_excel_cases - INFO - 从 20250923200055_类、方法介绍.xls 读取到 55 条用例
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:140" - get_merged_info - DEBUG - 工作表 'Sheet1' 合并单元格数量: 0
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:32" - __init__ - INFO - Excel工具初始化完成: 20250923200412_test_demo002.xls - Sheet1
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:182" - get_sheet_data_by_dict - INFO - 从工作表 'Sheet1' 读取到 10 条数据
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:221" - read_multiple_excel_cases - INFO - 从 20250923200412_test_demo002.xls 读取到 10 条用例
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:140" - get_merged_info - DEBUG - 工作表 'Sheet1' 合并单元格数量: 0
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:32" - __init__ - INFO - Excel工具初始化完成: test_demo.xls - Sheet1
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:182" - get_sheet_data_by_dict - INFO - 从工作表 'Sheet1' 读取到 3 条数据
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:221" - read_multiple_excel_cases - INFO - 从 test_demo.xls 读取到 3 条用例
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:140" - get_merged_info - DEBUG - 工作表 'Sheet1' 合并单元格数量: 0
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:32" - __init__ - INFO - Excel工具初始化完成: test_demo2.xls - Sheet1
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:182" - get_sheet_data_by_dict - INFO - 从工作表 'Sheet1' 读取到 3 条数据
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:221" - read_multiple_excel_cases - INFO - 从 test_demo2.xls 读取到 3 条用例
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:228" - read_multiple_excel_cases - INFO - 批量读取完成，共获取 71 条用例
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\sql_utils.py:36" - _get_connection - INFO - 连接数据库: 127.0.0.1:3308
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\sql_utils.py:39" - _get_connection - DEBUG - 数据库连接成功
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\sql_utils.py:82" - execute_query - DEBUG - 查询返回 16 条记录
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\test_runner\run_case.py:62" - get_test_suite - INFO - ({'case_id': 'part_1_case_01', 'case_info': [{'测试用例编号': 'case_01', '是否执行': '是', '模块名称': 'part_1', '测试用例名称': '注册接口_part_1', '测试用例步骤': 'step_01', '接口名称': '注册接口_part_1', '请求方式': 'POST', '请求地址': '/api/register', '请求参数(get)': '{}', '提交数据(post)': '{"email": "sydney@fife","password": "pistol"}', '取值方式': '正则匹配', '传值变量': 'total_pages', '取值代码': '"total_pages":(.+?)', '期望结果类型': 'json键是否存在', '期望结果': 'error', '是否通过': '通过'}]}, {'case_id': 'part_1_case_02', 'case_info': [{'测试用例编号': 'case_02', '是否执行': '是', '模块名称': 'part_1', '测试用例名称': '登录失败接口1_part_1', '测试用例步骤': 'step_01', '接口名称': '登录失败接口1_part_1', '请求方式': 'POST', '请求地址': '/api/login', '请求参数(get)': '{}', '提交数据(post)': '{"email": "123123"}', '取值方式': '无', '传值变量': '', '取值代码': '', '期望结果类型': 'json键是否存在', '期望结果': 'error', '是否通过': '通过'}]}, {'case_id': 'part_1_case_03', 'case_info': [{'测试用例编号': 'case_03', '是否执行': '是', '模块名称': 'part_1', '测试用例名称': '登录失败接口2_part_1', '测试用例步骤': 'step_01', '接口名称': '登录失败接口2_part_1', '请求方式': 'POST', '请求地址': '/api/login', '请求参数(get)': '{}', '提交数据(post)': '{"email": "12323"}', '取值方式': '无', '传值变量': '', '取值代码': '', '期望结果类型': 'json键是否存在', '期望结果': 'error', '是否通过': '通过'}]}, {'case_id': 'part_2_case_01', 'case_info': [{'测试用例编号': 'case_01', '是否执行': '是', '模块名称': 'part_2', '测试用例名称': '注册接口part_2', '测试用例步骤': 'step_01', '接口名称': '注册接口part_2', '请求方式': 'POST', '请求地址': '/api/register', '请求参数(get)': '{}', '提交数据(post)': '{"email": "sydney@fife","password": "pistol"}', '取值方式': '正则匹配', '传值变量': 'total_pages', '取值代码': '"total_pages":(.+?)', '期望结果类型': 'json键是否存在', '期望结果': 'total_pages', '是否通过': '失败'}]}, {'case_id': 'part_2_case_02', 'case_info': [{'测试用例编号': 'case_02', '是否执行': '是', '模块名称': 'part_2', '测试用例名称': '登录失败接口1_part_2', '测试用例步骤': 'step_01', '接口名称': '登录失败接口1_part_2', '请求方式': 'POST', '请求地址': '/api/login', '请求参数(get)': '{}', '提交数据(post)': '{"email": "123123"}', '取值方式': '无', '传值变量': '', '取值代码': '', '期望结果类型': 'json键是否存在', '期望结果': 'total_pages', '是否通过': '失败'}]}, {'case_id': 'part_2_case_03', 'case_info': [{'测试用例编号': 'case_03', '是否执行': '是', '模块名称': 'part_2', '测试用例名称': '登录失败接口2_part_2', '测试用例步骤': 'step_01', '接口名称': '登录失败接口2_part_2', '请求方式': 'POST', '请求地址': '/api/login', '请求参数(get)': '{}', '提交数据(post)': '{"email": "12323"}', '取值方式': '无', '传值变量': '', '取值代码': '', '期望结果类型': 'json键是否存在', '期望结果': 'total_pages', '是否通过': '通过'}]}, {'case_id': 'part_3_case_01', 'case_info': [{'测试用例编号': 'case_01', '是否执行': '是', '模块名称': 'part_3', '测试用例名称': '注册接口_part_1', '测试用例步骤': 'step_01', '接口名称': '注册接口_part_1', '请求方式': 'POST', '请求地址': '/api/register', '请求参数(get)': '{}', '提交数据(post)': '{"email": "sydney@fife","password": "pistol"}', '取值方式': '正则匹配', '传值变量': 'total_pages', '取值代码': '"total_pages":(.+?)', '期望结果类型': 'json键是否存在', '期望结果': 'error', '是否通过': '通过'}]}, {'case_id': 'part_3_case_02', 'case_info': [{'测试用例编号': 'case_02', '是否执行': '是', '模块名称': 'part_3', '测试用例名称': '登录失败接口1_part_3', '测试用例步骤': 'step_01', '接口名称': '登录失败接口1_part_3', '请求方式': 'POST', '请求地址': '/api/login', '请求参数(get)': '{}', '提交数据(post)': '{"email": "123123"}', '取值方式': '无', '传值变量': '', '取值代码': '', '期望结果类型': 'json键是否存在', '期望结果': 'error', '是否通过': '通过'}]}, {'case_id': 'part_3_case_03', 'case_info': [{'测试用例编号': 'case_03', '是否执行': '是', '模块名称': 'part_3', '测试用例名称': '登录失败接口2_part_3', '测试用例步骤': 'step_01', '接口名称': '登录失败接口2_part_3', '请求方式': 'POST', '请求地址': '/api/login', '请求参数(get)': '{}', '提交数据(post)': '{"email": "12323"}', '取值方式': '无', '传值变量': '', '取值代码': '', '期望结果类型': 'json键是否存在', '期望结果': 'error', '是否通过': '通过'}]}, {'case_id': 'part_3_case_04', 'case_info': [{'测试用例编号': 'case_04', '是否执行': '是', '模块名称': 'part_3', '测试用例名称': '登录失败接口3_part_3', '测试用例步骤': 'step_01', '接口名称': '登录失败接口3_part_3', '请求方式': 'POST', '请求地址': '/api/login', '请求参数(get)': '{}', '提交数据(post)': '{"email": "98477"}', '取值方式': '无', '传值变量': '', '取值代码': '', '期望结果类型': 'json键是否存在', '期望结果': 'error', '是否通过': '通过'}]}, {'case_id': 'part_3_case_05', 'case_info': [{'测试用例编号': 'case_05', '是否执行': '是', '模块名称': 'part_3', '测试用例名称': '登录失败接口4_part_3', '测试用例步骤': 'step_01', '接口名称': '登录失败接口4_part_3', '请求方式': 'POST', '请求地址': '/api/login', '请求参数(get)': '{}', '提交数据(post)': '{"email": "209277"}', '取值方式': '无', '传值变量': '', '取值代码': '', '期望结果类型': 'json键是否存在', '期望结果': 'error', '是否通过': '通过'}]}, {'case_id': 'part_3_case_06', 'case_info': [{'测试用例编号': 'case_06', '是否执行': '是', '模块名称': 'part_3', '测试用例名称': '登录失败接口5_part_3', '测试用例步骤': 'step_01', '接口名称': '登录失败接口5_part_3', '请求方式': 'POST', '请求地址': '/api/login', '请求参数(get)': '{}', '提交数据(post)': '{"email": "320077"}', '取值方式': '无', '传值变量': '', '取值代码': '', '期望结果类型': 'json键是否存在', '期望结果': 'error', '是否通过': '通过'}]}, {'case_id': 'part_3_case_07', 'case_info': [{'测试用例编号': 'case_07', '是否执行': '是', '模块名称': 'part_3', '测试用例名称': '登录失败接口6_part_3', '测试用例步骤': 'step_01', '接口名称': '登录失败接口6_part_3', '请求方式': 'POST', '请求地址': '/api/login', '请求参数(get)': '{}', '提交数据(post)': '{"email": "430877"}', '取值方式': '无', '传值变量': '', '取值代码': '', '期望结果类型': 'json键是否存在', '期望结果': 'error', '是否通过': '通过'}]}, {'case_id': 'part_3_case_08', 'case_info': [{'测试用例编号': 'case_08', '是否执行': '是', '模块名称': 'part_3', '测试用例名称': '登录失败接口7_part_3', '测试用例步骤': 'step_01', '接口名称': '登录失败接口7_part_3', '请求方式': 'POST', '请求地址': '/api/login', '请求参数(get)': '{}', '提交数据(post)': '{"email": "541677"}', '取值方式': '无', '传值变量': '', '取值代码': '', '期望结果类型': 'json键是否存在', '期望结果': 'error', '是否通过': '通过'}]}, {'case_id': 'part_3_case_09', 'case_info': [{'测试用例编号': 'case_09', '是否执行': '是', '模块名称': 'part_3', '测试用例名称': '登录失败接口8_part_3', '测试用例步骤': 'step_01', '接口名称': '登录失败接口8_part_3', '请求方式': 'POST', '请求地址': '/api/login', '请求参数(get)': '{}', '提交数据(post)': '{"email": "652477"}', '取值方式': '无', '传值变量': '', '取值代码': '', '期望结果类型': 'json键是否存在', '期望结果': 'error', '是否通过': '通过'}]}, {'case_id': 'part_3_case_10', 'case_info': [{'测试用例编号': 'case_10', '是否执行': '是', '模块名称': 'part_3', '测试用例名称': '登录失败接口9_part_3', '测试用例步骤': 'step_01', '接口名称': '登录失败接口9_part_3', '请求方式': 'POST', '请求地址': '/api/login', '请求参数(get)': '{}', '提交数据(post)': '{"email": "763277"}', '取值方式': '无', '传值变量': '', '取值代码': '', '期望结果类型': 'json键是否存在', '期望结果': 'error', '是否通过': '通过'}]})
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\test_runner\run_case.py:65" - get_test_suite - INFO - ['43bc9d6031']
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\test_runner\run_case.py:108" - get_test_suite - INFO - 用例收集完成，共 16 个用例
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\test_runner\run_case.py:124" - _get_report_path - INFO - 测试报告将保存至: D:\workdir\DjangoProject3\api_test_platform\test_reports\接口自动化测试报告_20250923201905\接口自动化测试报告.html
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\api_testcase\api_test.py:12" - setUp - INFO - 开始执行测试用例: test_part_1_case_01
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:22" - __init__ - DEBUG - 请求超时时间设置为: 10秒
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:151" - request - INFO - 开始处理请求步骤: step_01, 方式: POST
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:69" - __post - DEBUG - 发送POST请求: http://127.0.0.1:3000/api/register, 参数: {}, 提交数据: {"email": "sydney@fife","password": "pistol"}
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:77" - __post - WARNING - {}
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:86" - __post - DEBUG - POST响应状态码: 400, 响应内容: {"error":"Missing email or username"}
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:136" - _extract_variable - ERROR - 正则匹配失败: 表达式"total_pages":(.+?)未匹配到值
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\check_utils.py:150" - run_check - INFO - 开始执行断言: 类型=json键是否存在, 数据=error
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\check_utils.py:53" - check_key - DEBUG - JSON键检查通过，所有键存在: error
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:97" - __post - DEBUG - POST响应完整内容: {"error":"Missing email or username"}
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:98" - __post - DEBUG - POST响应Content-Type: application/json; charset=utf-8
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:167" - request - INFO - 请求步骤处理完成: step_01, 结果: 2
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:202" - request_by_step - ERROR - 步骤step_01执行失败，终止后续步骤
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\api_testcase\api_test.py:15" - tearDown - INFO - 测试用例执行结束: test_part_1_case_01
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\api_testcase\api_test.py:12" - setUp - INFO - 开始执行测试用例: test_part_1_case_02
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:22" - __init__ - DEBUG - 请求超时时间设置为: 10秒
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:151" - request - INFO - 开始处理请求步骤: step_01, 方式: POST
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:69" - __post - DEBUG - 发送POST请求: http://127.0.0.1:3000/api/login, 参数: {}, 提交数据: {"email": "123123"}
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:77" - __post - WARNING - {}
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:86" - __post - DEBUG - POST响应状态码: 400, 响应内容: {"error":"Missing email or username"}
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\check_utils.py:150" - run_check - INFO - 开始执行断言: 类型=json键是否存在, 数据=error
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\check_utils.py:53" - check_key - DEBUG - JSON键检查通过，所有键存在: error
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:97" - __post - DEBUG - POST响应完整内容: {"error":"Missing email or username"}
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:98" - __post - DEBUG - POST响应Content-Type: application/json; charset=utf-8
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:167" - request - INFO - 请求步骤处理完成: step_01, 结果: 2
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:202" - request_by_step - ERROR - 步骤step_01执行失败，终止后续步骤
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\api_testcase\api_test.py:15" - tearDown - INFO - 测试用例执行结束: test_part_1_case_02
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\api_testcase\api_test.py:12" - setUp - INFO - 开始执行测试用例: test_part_1_case_03
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:22" - __init__ - DEBUG - 请求超时时间设置为: 10秒
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:151" - request - INFO - 开始处理请求步骤: step_01, 方式: POST
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:69" - __post - DEBUG - 发送POST请求: http://127.0.0.1:3000/api/login, 参数: {}, 提交数据: {"email": "12323"}
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:77" - __post - WARNING - {}
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:86" - __post - DEBUG - POST响应状态码: 400, 响应内容: {"error":"Missing email or username"}
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\check_utils.py:150" - run_check - INFO - 开始执行断言: 类型=json键是否存在, 数据=error
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\check_utils.py:53" - check_key - DEBUG - JSON键检查通过，所有键存在: error
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:97" - __post - DEBUG - POST响应完整内容: {"error":"Missing email or username"}
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:98" - __post - DEBUG - POST响应Content-Type: application/json; charset=utf-8
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:167" - request - INFO - 请求步骤处理完成: step_01, 结果: 2
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:202" - request_by_step - ERROR - 步骤step_01执行失败，终止后续步骤
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\api_testcase\api_test.py:15" - tearDown - INFO - 测试用例执行结束: test_part_1_case_03
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\api_testcase\api_test.py:12" - setUp - INFO - 开始执行测试用例: test_part_2_case_01
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:22" - __init__ - DEBUG - 请求超时时间设置为: 10秒
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:151" - request - INFO - 开始处理请求步骤: step_01, 方式: POST
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:69" - __post - DEBUG - 发送POST请求: http://127.0.0.1:3000/api/register, 参数: {}, 提交数据: {"email": "sydney@fife","password": "pistol"}
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:77" - __post - WARNING - {}
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:86" - __post - DEBUG - POST响应状态码: 400, 响应内容: {"error":"Missing email or username"}
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:136" - _extract_variable - ERROR - 正则匹配失败: 表达式"total_pages":(.+?)未匹配到值
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\check_utils.py:150" - run_check - INFO - 开始执行断言: 类型=json键是否存在, 数据=total_pages
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\check_utils.py:57" - check_key - ERROR - JSON键检查失败，缺失键: total_pages
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:97" - __post - DEBUG - POST响应完整内容: {"error":"Missing email or username"}
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:98" - __post - DEBUG - POST响应Content-Type: application/json; charset=utf-8
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:167" - request - INFO - 请求步骤处理完成: step_01, 结果: 4
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:202" - request_by_step - ERROR - 步骤step_01执行失败，终止后续步骤
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\api_testcase\api_test.py:15" - tearDown - INFO - 测试用例执行结束: test_part_2_case_01
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\api_testcase\api_test.py:12" - setUp - INFO - 开始执行测试用例: test_part_2_case_02
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:22" - __init__ - DEBUG - 请求超时时间设置为: 10秒
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:151" - request - INFO - 开始处理请求步骤: step_01, 方式: POST
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:69" - __post - DEBUG - 发送POST请求: http://127.0.0.1:3000/api/login, 参数: {}, 提交数据: {"email": "123123"}
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:77" - __post - WARNING - {}
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:86" - __post - DEBUG - POST响应状态码: 400, 响应内容: {"error":"Missing email or username"}
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\check_utils.py:150" - run_check - INFO - 开始执行断言: 类型=json键是否存在, 数据=total_pages
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\check_utils.py:57" - check_key - ERROR - JSON键检查失败，缺失键: total_pages
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:97" - __post - DEBUG - POST响应完整内容: {"error":"Missing email or username"}
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:98" - __post - DEBUG - POST响应Content-Type: application/json; charset=utf-8
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:167" - request - INFO - 请求步骤处理完成: step_01, 结果: 4
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:202" - request_by_step - ERROR - 步骤step_01执行失败，终止后续步骤
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\api_testcase\api_test.py:15" - tearDown - INFO - 测试用例执行结束: test_part_2_case_02
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\api_testcase\api_test.py:12" - setUp - INFO - 开始执行测试用例: test_part_2_case_03
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:22" - __init__ - DEBUG - 请求超时时间设置为: 10秒
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:151" - request - INFO - 开始处理请求步骤: step_01, 方式: POST
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:69" - __post - DEBUG - 发送POST请求: http://127.0.0.1:3000/api/login, 参数: {}, 提交数据: {"email": "12323"}
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:77" - __post - WARNING - {}
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:86" - __post - DEBUG - POST响应状态码: 400, 响应内容: {"error":"Missing email or username"}
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\check_utils.py:150" - run_check - INFO - 开始执行断言: 类型=json键是否存在, 数据=total_pages
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\check_utils.py:57" - check_key - ERROR - JSON键检查失败，缺失键: total_pages
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:97" - __post - DEBUG - POST响应完整内容: {"error":"Missing email or username"}
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:98" - __post - DEBUG - POST响应Content-Type: application/json; charset=utf-8
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:167" - request - INFO - 请求步骤处理完成: step_01, 结果: 4
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:202" - request_by_step - ERROR - 步骤step_01执行失败，终止后续步骤
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\api_testcase\api_test.py:15" - tearDown - INFO - 测试用例执行结束: test_part_2_case_03
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\api_testcase\api_test.py:12" - setUp - INFO - 开始执行测试用例: test_part_3_case_01
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:22" - __init__ - DEBUG - 请求超时时间设置为: 10秒
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:151" - request - INFO - 开始处理请求步骤: step_01, 方式: POST
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:69" - __post - DEBUG - 发送POST请求: http://127.0.0.1:3000/api/register, 参数: {}, 提交数据: {"email": "sydney@fife","password": "pistol"}
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:77" - __post - WARNING - {}
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:86" - __post - DEBUG - POST响应状态码: 400, 响应内容: {"error":"Missing email or username"}
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:136" - _extract_variable - ERROR - 正则匹配失败: 表达式"total_pages":(.+?)未匹配到值
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\check_utils.py:150" - run_check - INFO - 开始执行断言: 类型=json键是否存在, 数据=error
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\check_utils.py:53" - check_key - DEBUG - JSON键检查通过，所有键存在: error
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:97" - __post - DEBUG - POST响应完整内容: {"error":"Missing email or username"}
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:98" - __post - DEBUG - POST响应Content-Type: application/json; charset=utf-8
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:167" - request - INFO - 请求步骤处理完成: step_01, 结果: 2
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:202" - request_by_step - ERROR - 步骤step_01执行失败，终止后续步骤
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\api_testcase\api_test.py:15" - tearDown - INFO - 测试用例执行结束: test_part_3_case_01
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\api_testcase\api_test.py:12" - setUp - INFO - 开始执行测试用例: test_part_3_case_02
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:22" - __init__ - DEBUG - 请求超时时间设置为: 10秒
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:151" - request - INFO - 开始处理请求步骤: step_01, 方式: POST
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:69" - __post - DEBUG - 发送POST请求: http://127.0.0.1:3000/api/login, 参数: {}, 提交数据: {"email": "123123"}
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:77" - __post - WARNING - {}
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:86" - __post - DEBUG - POST响应状态码: 400, 响应内容: {"error":"Missing email or username"}
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\check_utils.py:150" - run_check - INFO - 开始执行断言: 类型=json键是否存在, 数据=error
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\check_utils.py:53" - check_key - DEBUG - JSON键检查通过，所有键存在: error
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:97" - __post - DEBUG - POST响应完整内容: {"error":"Missing email or username"}
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:98" - __post - DEBUG - POST响应Content-Type: application/json; charset=utf-8
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:167" - request - INFO - 请求步骤处理完成: step_01, 结果: 2
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:202" - request_by_step - ERROR - 步骤step_01执行失败，终止后续步骤
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\api_testcase\api_test.py:15" - tearDown - INFO - 测试用例执行结束: test_part_3_case_02
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\api_testcase\api_test.py:12" - setUp - INFO - 开始执行测试用例: test_part_3_case_03
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:22" - __init__ - DEBUG - 请求超时时间设置为: 10秒
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:151" - request - INFO - 开始处理请求步骤: step_01, 方式: POST
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:69" - __post - DEBUG - 发送POST请求: http://127.0.0.1:3000/api/login, 参数: {}, 提交数据: {"email": "12323"}
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:77" - __post - WARNING - {}
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:86" - __post - DEBUG - POST响应状态码: 400, 响应内容: {"error":"Missing email or username"}
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\check_utils.py:150" - run_check - INFO - 开始执行断言: 类型=json键是否存在, 数据=error
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\check_utils.py:53" - check_key - DEBUG - JSON键检查通过，所有键存在: error
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:97" - __post - DEBUG - POST响应完整内容: {"error":"Missing email or username"}
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:98" - __post - DEBUG - POST响应Content-Type: application/json; charset=utf-8
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:167" - request - INFO - 请求步骤处理完成: step_01, 结果: 2
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:202" - request_by_step - ERROR - 步骤step_01执行失败，终止后续步骤
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\api_testcase\api_test.py:15" - tearDown - INFO - 测试用例执行结束: test_part_3_case_03
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\api_testcase\api_test.py:12" - setUp - INFO - 开始执行测试用例: test_part_3_case_04
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:22" - __init__ - DEBUG - 请求超时时间设置为: 10秒
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:151" - request - INFO - 开始处理请求步骤: step_01, 方式: POST
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:69" - __post - DEBUG - 发送POST请求: http://127.0.0.1:3000/api/login, 参数: {}, 提交数据: {"email": "98477"}
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:77" - __post - WARNING - {}
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:86" - __post - DEBUG - POST响应状态码: 400, 响应内容: {"error":"Missing email or username"}
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\check_utils.py:150" - run_check - INFO - 开始执行断言: 类型=json键是否存在, 数据=error
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\check_utils.py:53" - check_key - DEBUG - JSON键检查通过，所有键存在: error
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:97" - __post - DEBUG - POST响应完整内容: {"error":"Missing email or username"}
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:98" - __post - DEBUG - POST响应Content-Type: application/json; charset=utf-8
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:167" - request - INFO - 请求步骤处理完成: step_01, 结果: 2
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:202" - request_by_step - ERROR - 步骤step_01执行失败，终止后续步骤
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\api_testcase\api_test.py:15" - tearDown - INFO - 测试用例执行结束: test_part_3_case_04
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\api_testcase\api_test.py:12" - setUp - INFO - 开始执行测试用例: test_part_3_case_05
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:22" - __init__ - DEBUG - 请求超时时间设置为: 10秒
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:151" - request - INFO - 开始处理请求步骤: step_01, 方式: POST
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:69" - __post - DEBUG - 发送POST请求: http://127.0.0.1:3000/api/login, 参数: {}, 提交数据: {"email": "209277"}
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:77" - __post - WARNING - {}
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:86" - __post - DEBUG - POST响应状态码: 400, 响应内容: {"error":"Missing email or username"}
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\check_utils.py:150" - run_check - INFO - 开始执行断言: 类型=json键是否存在, 数据=error
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\check_utils.py:53" - check_key - DEBUG - JSON键检查通过，所有键存在: error
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:97" - __post - DEBUG - POST响应完整内容: {"error":"Missing email or username"}
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:98" - __post - DEBUG - POST响应Content-Type: application/json; charset=utf-8
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:167" - request - INFO - 请求步骤处理完成: step_01, 结果: 2
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:202" - request_by_step - ERROR - 步骤step_01执行失败，终止后续步骤
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\api_testcase\api_test.py:15" - tearDown - INFO - 测试用例执行结束: test_part_3_case_05
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\api_testcase\api_test.py:12" - setUp - INFO - 开始执行测试用例: test_part_3_case_06
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:22" - __init__ - DEBUG - 请求超时时间设置为: 10秒
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:151" - request - INFO - 开始处理请求步骤: step_01, 方式: POST
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:69" - __post - DEBUG - 发送POST请求: http://127.0.0.1:3000/api/login, 参数: {}, 提交数据: {"email": "320077"}
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:77" - __post - WARNING - {}
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:86" - __post - DEBUG - POST响应状态码: 400, 响应内容: {"error":"Missing email or username"}
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\check_utils.py:150" - run_check - INFO - 开始执行断言: 类型=json键是否存在, 数据=error
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\check_utils.py:53" - check_key - DEBUG - JSON键检查通过，所有键存在: error
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:97" - __post - DEBUG - POST响应完整内容: {"error":"Missing email or username"}
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:98" - __post - DEBUG - POST响应Content-Type: application/json; charset=utf-8
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:167" - request - INFO - 请求步骤处理完成: step_01, 结果: 2
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:202" - request_by_step - ERROR - 步骤step_01执行失败，终止后续步骤
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\api_testcase\api_test.py:15" - tearDown - INFO - 测试用例执行结束: test_part_3_case_06
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\api_testcase\api_test.py:12" - setUp - INFO - 开始执行测试用例: test_part_3_case_07
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:22" - __init__ - DEBUG - 请求超时时间设置为: 10秒
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:151" - request - INFO - 开始处理请求步骤: step_01, 方式: POST
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:69" - __post - DEBUG - 发送POST请求: http://127.0.0.1:3000/api/login, 参数: {}, 提交数据: {"email": "430877"}
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:77" - __post - WARNING - {}
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:86" - __post - DEBUG - POST响应状态码: 400, 响应内容: {"error":"Missing email or username"}
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\check_utils.py:150" - run_check - INFO - 开始执行断言: 类型=json键是否存在, 数据=error
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\check_utils.py:53" - check_key - DEBUG - JSON键检查通过，所有键存在: error
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:97" - __post - DEBUG - POST响应完整内容: {"error":"Missing email or username"}
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:98" - __post - DEBUG - POST响应Content-Type: application/json; charset=utf-8
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:167" - request - INFO - 请求步骤处理完成: step_01, 结果: 2
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:202" - request_by_step - ERROR - 步骤step_01执行失败，终止后续步骤
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\api_testcase\api_test.py:15" - tearDown - INFO - 测试用例执行结束: test_part_3_case_07
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\api_testcase\api_test.py:12" - setUp - INFO - 开始执行测试用例: test_part_3_case_08
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:22" - __init__ - DEBUG - 请求超时时间设置为: 10秒
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:151" - request - INFO - 开始处理请求步骤: step_01, 方式: POST
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:69" - __post - DEBUG - 发送POST请求: http://127.0.0.1:3000/api/login, 参数: {}, 提交数据: {"email": "541677"}
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:77" - __post - WARNING - {}
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:86" - __post - DEBUG - POST响应状态码: 400, 响应内容: {"error":"Missing email or username"}
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\check_utils.py:150" - run_check - INFO - 开始执行断言: 类型=json键是否存在, 数据=error
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\check_utils.py:53" - check_key - DEBUG - JSON键检查通过，所有键存在: error
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:97" - __post - DEBUG - POST响应完整内容: {"error":"Missing email or username"}
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:98" - __post - DEBUG - POST响应Content-Type: application/json; charset=utf-8
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:167" - request - INFO - 请求步骤处理完成: step_01, 结果: 2
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:202" - request_by_step - ERROR - 步骤step_01执行失败，终止后续步骤
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\api_testcase\api_test.py:15" - tearDown - INFO - 测试用例执行结束: test_part_3_case_08
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\api_testcase\api_test.py:12" - setUp - INFO - 开始执行测试用例: test_part_3_case_09
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:22" - __init__ - DEBUG - 请求超时时间设置为: 10秒
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:151" - request - INFO - 开始处理请求步骤: step_01, 方式: POST
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:69" - __post - DEBUG - 发送POST请求: http://127.0.0.1:3000/api/login, 参数: {}, 提交数据: {"email": "652477"}
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:77" - __post - WARNING - {}
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:86" - __post - DEBUG - POST响应状态码: 400, 响应内容: {"error":"Missing email or username"}
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\check_utils.py:150" - run_check - INFO - 开始执行断言: 类型=json键是否存在, 数据=error
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\check_utils.py:53" - check_key - DEBUG - JSON键检查通过，所有键存在: error
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:97" - __post - DEBUG - POST响应完整内容: {"error":"Missing email or username"}
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:98" - __post - DEBUG - POST响应Content-Type: application/json; charset=utf-8
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:167" - request - INFO - 请求步骤处理完成: step_01, 结果: 2
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:202" - request_by_step - ERROR - 步骤step_01执行失败，终止后续步骤
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\api_testcase\api_test.py:15" - tearDown - INFO - 测试用例执行结束: test_part_3_case_09
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\api_testcase\api_test.py:12" - setUp - INFO - 开始执行测试用例: test_part_3_case_10
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:22" - __init__ - DEBUG - 请求超时时间设置为: 10秒
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:151" - request - INFO - 开始处理请求步骤: step_01, 方式: POST
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:69" - __post - DEBUG - 发送POST请求: http://127.0.0.1:3000/api/login, 参数: {}, 提交数据: {"email": "763277"}
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:77" - __post - WARNING - {}
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:86" - __post - DEBUG - POST响应状态码: 400, 响应内容: {"error":"Missing email or username"}
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\check_utils.py:150" - run_check - INFO - 开始执行断言: 类型=json键是否存在, 数据=error
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\check_utils.py:53" - check_key - DEBUG - JSON键检查通过，所有键存在: error
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:97" - __post - DEBUG - POST响应完整内容: {"error":"Missing email or username"}
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:98" - __post - DEBUG - POST响应Content-Type: application/json; charset=utf-8
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:167" - request - INFO - 请求步骤处理完成: step_01, 结果: 2
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\requests_utils.py:202" - request_by_step - ERROR - 步骤step_01执行失败，终止后续步骤
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\api_testcase\api_test.py:15" - tearDown - INFO - 测试用例执行结束: test_part_3_case_10
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\test_runner\run_case.py:155" - run - INFO - ============================================================
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\test_runner\run_case.py:156" - run - INFO - 测试执行完成，结果统计:
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\test_runner\run_case.py:157" - run - INFO - 总用例数: 16
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\test_runner\run_case.py:158" - run - INFO - 通过: 13
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\test_runner\run_case.py:159" - run - INFO - 失败: 3
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\test_runner\run_case.py:160" - run - INFO - 错误: 0
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\test_runner\run_case.py:161" - run - INFO - ============================================================
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\api_platform\api_auto\views.py:211" - run_all_cases - INFO - 准备发送测试报告邮件
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\test_runner\run_case.py:51" - get_test_suite - INFO - 开始收集测试用例，路径: D:\workdir\DjangoProject3\api_test_platform\api_testcase
2025-09-23 20:19:05 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\test_runner\run_case.py:57" - get_test_suite - INFO - 指定用例ID: None
2025-09-23 20:19:25 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:140" - get_merged_info - DEBUG - 工作表 'Sheet1' 合并单元格数量: 0
2025-09-23 20:19:25 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:32" - __init__ - INFO - Excel工具初始化完成: test_demo.xls - Sheet1
2025-09-23 20:19:25 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:209" - read_multiple_excel_cases - INFO - 发现 4 个Excel文件，开始读取用例...
2025-09-23 20:19:25 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:140" - get_merged_info - DEBUG - 工作表 'Sheet1' 合并单元格数量: 10
2025-09-23 20:19:25 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:32" - __init__ - INFO - Excel工具初始化完成: 20250923200055_类、方法介绍.xls - Sheet1
2025-09-23 20:19:25 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(1,0)属于合并区域，取值(1,0)
2025-09-23 20:19:25 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(1,1)属于合并区域，取值(1,0)
2025-09-23 20:19:25 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(1,2)属于合并区域，取值(1,0)
2025-09-23 20:19:25 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(1,3)属于合并区域，取值(1,0)
2025-09-23 20:19:25 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(1,4)属于合并区域，取值(1,0)
2025-09-23 20:19:25 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(1,5)属于合并区域，取值(1,0)
2025-09-23 20:19:25 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(1,6)属于合并区域，取值(1,0)
2025-09-23 20:19:25 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(8,0)属于合并区域，取值(8,0)
2025-09-23 20:19:25 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(8,1)属于合并区域，取值(8,0)
2025-09-23 20:19:25 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(8,2)属于合并区域，取值(8,0)
2025-09-23 20:19:25 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(8,3)属于合并区域，取值(8,0)
2025-09-23 20:19:25 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(8,4)属于合并区域，取值(8,0)
2025-09-23 20:19:25 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(8,5)属于合并区域，取值(8,0)
2025-09-23 20:19:25 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(8,6)属于合并区域，取值(8,0)
2025-09-23 20:19:25 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(16,0)属于合并区域，取值(16,0)
2025-09-23 20:19:25 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(16,1)属于合并区域，取值(16,0)
2025-09-23 20:19:25 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(16,2)属于合并区域，取值(16,0)
2025-09-23 20:19:25 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(16,3)属于合并区域，取值(16,0)
2025-09-23 20:19:25 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(16,4)属于合并区域，取值(16,0)
2025-09-23 20:19:25 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(16,5)属于合并区域，取值(16,0)
2025-09-23 20:19:25 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(16,6)属于合并区域，取值(16,0)
2025-09-23 20:19:25 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(24,0)属于合并区域，取值(24,0)
2025-09-23 20:19:25 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(24,1)属于合并区域，取值(24,0)
2025-09-23 20:19:25 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(24,2)属于合并区域，取值(24,0)
2025-09-23 20:19:25 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(24,3)属于合并区域，取值(24,0)
2025-09-23 20:19:25 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(24,4)属于合并区域，取值(24,0)
2025-09-23 20:19:25 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(24,5)属于合并区域，取值(24,0)
2025-09-23 20:19:25 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(24,6)属于合并区域，取值(24,0)
2025-09-23 20:19:25 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(30,0)属于合并区域，取值(30,0)
2025-09-23 20:19:25 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(30,1)属于合并区域，取值(30,0)
2025-09-23 20:19:25 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(30,2)属于合并区域，取值(30,0)
2025-09-23 20:19:25 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(30,3)属于合并区域，取值(30,0)
2025-09-23 20:19:25 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(30,4)属于合并区域，取值(30,0)
2025-09-23 20:19:25 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(30,5)属于合并区域，取值(30,0)
2025-09-23 20:19:25 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(30,6)属于合并区域，取值(30,0)
2025-09-23 20:19:25 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(35,0)属于合并区域，取值(35,0)
2025-09-23 20:19:25 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(35,1)属于合并区域，取值(35,0)
2025-09-23 20:19:25 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(35,2)属于合并区域，取值(35,0)
2025-09-23 20:19:25 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(35,3)属于合并区域，取值(35,0)
2025-09-23 20:19:25 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(35,4)属于合并区域，取值(35,0)
2025-09-23 20:19:25 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(35,5)属于合并区域，取值(35,0)
2025-09-23 20:19:25 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(35,6)属于合并区域，取值(35,0)
2025-09-23 20:19:25 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(38,0)属于合并区域，取值(38,0)
2025-09-23 20:19:25 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(38,1)属于合并区域，取值(38,0)
2025-09-23 20:19:25 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(38,2)属于合并区域，取值(38,0)
2025-09-23 20:19:25 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(38,3)属于合并区域，取值(38,0)
2025-09-23 20:19:25 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(38,4)属于合并区域，取值(38,0)
2025-09-23 20:19:25 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(38,5)属于合并区域，取值(38,0)
2025-09-23 20:19:25 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(38,6)属于合并区域，取值(38,0)
2025-09-23 20:19:25 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(41,0)属于合并区域，取值(41,0)
2025-09-23 20:19:25 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(41,1)属于合并区域，取值(41,0)
2025-09-23 20:19:25 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(41,2)属于合并区域，取值(41,0)
2025-09-23 20:19:25 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(41,3)属于合并区域，取值(41,0)
2025-09-23 20:19:25 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(41,4)属于合并区域，取值(41,0)
2025-09-23 20:19:25 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(41,5)属于合并区域，取值(41,0)
2025-09-23 20:19:25 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(41,6)属于合并区域，取值(41,0)
2025-09-23 20:19:25 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(45,0)属于合并区域，取值(45,0)
2025-09-23 20:19:25 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(45,1)属于合并区域，取值(45,0)
2025-09-23 20:19:25 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(45,2)属于合并区域，取值(45,0)
2025-09-23 20:19:25 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(45,3)属于合并区域，取值(45,0)
2025-09-23 20:19:25 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(45,4)属于合并区域，取值(45,0)
2025-09-23 20:19:25 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(45,5)属于合并区域，取值(45,0)
2025-09-23 20:19:25 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(45,6)属于合并区域，取值(45,0)
2025-09-23 20:19:25 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(50,0)属于合并区域，取值(50,0)
2025-09-23 20:19:25 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(50,1)属于合并区域，取值(50,0)
2025-09-23 20:19:25 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(50,2)属于合并区域，取值(50,0)
2025-09-23 20:19:25 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(50,3)属于合并区域，取值(50,0)
2025-09-23 20:19:25 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(50,4)属于合并区域，取值(50,0)
2025-09-23 20:19:25 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(50,5)属于合并区域，取值(50,0)
2025-09-23 20:19:25 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:149" - get_merged_cell_value_from_cell - DEBUG - 单元格(50,6)属于合并区域，取值(50,0)
2025-09-23 20:19:25 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:182" - get_sheet_data_by_dict - INFO - 从工作表 'Sheet1' 读取到 55 条数据
2025-09-23 20:19:25 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:221" - read_multiple_excel_cases - INFO - 从 20250923200055_类、方法介绍.xls 读取到 55 条用例
2025-09-23 20:19:25 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:140" - get_merged_info - DEBUG - 工作表 'Sheet1' 合并单元格数量: 0
2025-09-23 20:19:25 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:32" - __init__ - INFO - Excel工具初始化完成: 20250923200412_test_demo002.xls - Sheet1
2025-09-23 20:19:25 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:182" - get_sheet_data_by_dict - INFO - 从工作表 'Sheet1' 读取到 10 条数据
2025-09-23 20:19:25 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:221" - read_multiple_excel_cases - INFO - 从 20250923200412_test_demo002.xls 读取到 10 条用例
2025-09-23 20:19:25 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:140" - get_merged_info - DEBUG - 工作表 'Sheet1' 合并单元格数量: 0
2025-09-23 20:19:25 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:32" - __init__ - INFO - Excel工具初始化完成: test_demo.xls - Sheet1
2025-09-23 20:19:25 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:182" - get_sheet_data_by_dict - INFO - 从工作表 'Sheet1' 读取到 3 条数据
2025-09-23 20:19:25 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:221" - read_multiple_excel_cases - INFO - 从 test_demo.xls 读取到 3 条用例
2025-09-23 20:19:25 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:140" - get_merged_info - DEBUG - 工作表 'Sheet1' 合并单元格数量: 0
2025-09-23 20:19:25 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:32" - __init__ - INFO - Excel工具初始化完成: test_demo2.xls - Sheet1
2025-09-23 20:19:25 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:182" - get_sheet_data_by_dict - INFO - 从工作表 'Sheet1' 读取到 3 条数据
2025-09-23 20:19:25 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:221" - read_multiple_excel_cases - INFO - 从 test_demo2.xls 读取到 3 条用例
2025-09-23 20:19:25 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\excel_utils.py:228" - read_multiple_excel_cases - INFO - 批量读取完成，共获取 71 条用例
2025-09-23 20:19:25 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\sql_utils.py:36" - _get_connection - INFO - 连接数据库: 127.0.0.1:3308
2025-09-23 20:19:25 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\sql_utils.py:39" - _get_connection - DEBUG - 数据库连接成功
2025-09-23 20:19:25 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\sql_utils.py:82" - execute_query - DEBUG - 查询返回 16 条记录
2025-09-23 20:19:25 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\test_runner\run_case.py:62" - get_test_suite - INFO - ({'case_id': 'part_1_case_01', 'case_info': [{'测试用例编号': 'case_01', '是否执行': '是', '模块名称': 'part_1', '测试用例名称': '注册接口_part_1', '测试用例步骤': 'step_01', '接口名称': '注册接口_part_1', '请求方式': 'POST', '请求地址': '/api/register', '请求参数(get)': '{}', '提交数据(post)': '{"email": "sydney@fife","password": "pistol"}', '取值方式': '正则匹配', '传值变量': 'total_pages', '取值代码': '"total_pages":(.+?)', '期望结果类型': 'json键是否存在', '期望结果': 'error', '是否通过': '通过'}]}, {'case_id': 'part_1_case_02', 'case_info': [{'测试用例编号': 'case_02', '是否执行': '是', '模块名称': 'part_1', '测试用例名称': '登录失败接口1_part_1', '测试用例步骤': 'step_01', '接口名称': '登录失败接口1_part_1', '请求方式': 'POST', '请求地址': '/api/login', '请求参数(get)': '{}', '提交数据(post)': '{"email": "123123"}', '取值方式': '无', '传值变量': '', '取值代码': '', '期望结果类型': 'json键是否存在', '期望结果': 'error', '是否通过': '通过'}]}, {'case_id': 'part_1_case_03', 'case_info': [{'测试用例编号': 'case_03', '是否执行': '是', '模块名称': 'part_1', '测试用例名称': '登录失败接口2_part_1', '测试用例步骤': 'step_01', '接口名称': '登录失败接口2_part_1', '请求方式': 'POST', '请求地址': '/api/login', '请求参数(get)': '{}', '提交数据(post)': '{"email": "12323"}', '取值方式': '无', '传值变量': '', '取值代码': '', '期望结果类型': 'json键是否存在', '期望结果': 'error', '是否通过': '通过'}]}, {'case_id': 'part_2_case_01', 'case_info': [{'测试用例编号': 'case_01', '是否执行': '是', '模块名称': 'part_2', '测试用例名称': '注册接口part_2', '测试用例步骤': 'step_01', '接口名称': '注册接口part_2', '请求方式': 'POST', '请求地址': '/api/register', '请求参数(get)': '{}', '提交数据(post)': '{"email": "sydney@fife","password": "pistol"}', '取值方式': '正则匹配', '传值变量': 'total_pages', '取值代码': '"total_pages":(.+?)', '期望结果类型': 'json键是否存在', '期望结果': 'total_pages', '是否通过': '失败'}]}, {'case_id': 'part_2_case_02', 'case_info': [{'测试用例编号': 'case_02', '是否执行': '是', '模块名称': 'part_2', '测试用例名称': '登录失败接口1_part_2', '测试用例步骤': 'step_01', '接口名称': '登录失败接口1_part_2', '请求方式': 'POST', '请求地址': '/api/login', '请求参数(get)': '{}', '提交数据(post)': '{"email": "123123"}', '取值方式': '无', '传值变量': '', '取值代码': '', '期望结果类型': 'json键是否存在', '期望结果': 'total_pages', '是否通过': '失败'}]}, {'case_id': 'part_2_case_03', 'case_info': [{'测试用例编号': 'case_03', '是否执行': '是', '模块名称': 'part_2', '测试用例名称': '登录失败接口2_part_2', '测试用例步骤': 'step_01', '接口名称': '登录失败接口2_part_2', '请求方式': 'POST', '请求地址': '/api/login', '请求参数(get)': '{}', '提交数据(post)': '{"email": "12323"}', '取值方式': '无', '传值变量': '', '取值代码': '', '期望结果类型': 'json键是否存在', '期望结果': 'total_pages', '是否通过': '通过'}]}, {'case_id': 'part_3_case_01', 'case_info': [{'测试用例编号': 'case_01', '是否执行': '是', '模块名称': 'part_3', '测试用例名称': '注册接口_part_1', '测试用例步骤': 'step_01', '接口名称': '注册接口_part_1', '请求方式': 'POST', '请求地址': '/api/register', '请求参数(get)': '{}', '提交数据(post)': '{"email": "sydney@fife","password": "pistol"}', '取值方式': '正则匹配', '传值变量': 'total_pages', '取值代码': '"total_pages":(.+?)', '期望结果类型': 'json键是否存在', '期望结果': 'error', '是否通过': '通过'}]}, {'case_id': 'part_3_case_02', 'case_info': [{'测试用例编号': 'case_02', '是否执行': '是', '模块名称': 'part_3', '测试用例名称': '登录失败接口1_part_3', '测试用例步骤': 'step_01', '接口名称': '登录失败接口1_part_3', '请求方式': 'POST', '请求地址': '/api/login', '请求参数(get)': '{}', '提交数据(post)': '{"email": "123123"}', '取值方式': '无', '传值变量': '', '取值代码': '', '期望结果类型': 'json键是否存在', '期望结果': 'error', '是否通过': '通过'}]}, {'case_id': 'part_3_case_03', 'case_info': [{'测试用例编号': 'case_03', '是否执行': '是', '模块名称': 'part_3', '测试用例名称': '登录失败接口2_part_3', '测试用例步骤': 'step_01', '接口名称': '登录失败接口2_part_3', '请求方式': 'POST', '请求地址': '/api/login', '请求参数(get)': '{}', '提交数据(post)': '{"email": "12323"}', '取值方式': '无', '传值变量': '', '取值代码': '', '期望结果类型': 'json键是否存在', '期望结果': 'error', '是否通过': '通过'}]}, {'case_id': 'part_3_case_04', 'case_info': [{'测试用例编号': 'case_04', '是否执行': '是', '模块名称': 'part_3', '测试用例名称': '登录失败接口3_part_3', '测试用例步骤': 'step_01', '接口名称': '登录失败接口3_part_3', '请求方式': 'POST', '请求地址': '/api/login', '请求参数(get)': '{}', '提交数据(post)': '{"email": "98477"}', '取值方式': '无', '传值变量': '', '取值代码': '', '期望结果类型': 'json键是否存在', '期望结果': 'error', '是否通过': '通过'}]}, {'case_id': 'part_3_case_05', 'case_info': [{'测试用例编号': 'case_05', '是否执行': '是', '模块名称': 'part_3', '测试用例名称': '登录失败接口4_part_3', '测试用例步骤': 'step_01', '接口名称': '登录失败接口4_part_3', '请求方式': 'POST', '请求地址': '/api/login', '请求参数(get)': '{}', '提交数据(post)': '{"email": "209277"}', '取值方式': '无', '传值变量': '', '取值代码': '', '期望结果类型': 'json键是否存在', '期望结果': 'error', '是否通过': '通过'}]}, {'case_id': 'part_3_case_06', 'case_info': [{'测试用例编号': 'case_06', '是否执行': '是', '模块名称': 'part_3', '测试用例名称': '登录失败接口5_part_3', '测试用例步骤': 'step_01', '接口名称': '登录失败接口5_part_3', '请求方式': 'POST', '请求地址': '/api/login', '请求参数(get)': '{}', '提交数据(post)': '{"email": "320077"}', '取值方式': '无', '传值变量': '', '取值代码': '', '期望结果类型': 'json键是否存在', '期望结果': 'error', '是否通过': '通过'}]}, {'case_id': 'part_3_case_07', 'case_info': [{'测试用例编号': 'case_07', '是否执行': '是', '模块名称': 'part_3', '测试用例名称': '登录失败接口6_part_3', '测试用例步骤': 'step_01', '接口名称': '登录失败接口6_part_3', '请求方式': 'POST', '请求地址': '/api/login', '请求参数(get)': '{}', '提交数据(post)': '{"email": "430877"}', '取值方式': '无', '传值变量': '', '取值代码': '', '期望结果类型': 'json键是否存在', '期望结果': 'error', '是否通过': '通过'}]}, {'case_id': 'part_3_case_08', 'case_info': [{'测试用例编号': 'case_08', '是否执行': '是', '模块名称': 'part_3', '测试用例名称': '登录失败接口7_part_3', '测试用例步骤': 'step_01', '接口名称': '登录失败接口7_part_3', '请求方式': 'POST', '请求地址': '/api/login', '请求参数(get)': '{}', '提交数据(post)': '{"email": "541677"}', '取值方式': '无', '传值变量': '', '取值代码': '', '期望结果类型': 'json键是否存在', '期望结果': 'error', '是否通过': '通过'}]}, {'case_id': 'part_3_case_09', 'case_info': [{'测试用例编号': 'case_09', '是否执行': '是', '模块名称': 'part_3', '测试用例名称': '登录失败接口8_part_3', '测试用例步骤': 'step_01', '接口名称': '登录失败接口8_part_3', '请求方式': 'POST', '请求地址': '/api/login', '请求参数(get)': '{}', '提交数据(post)': '{"email": "652477"}', '取值方式': '无', '传值变量': '', '取值代码': '', '期望结果类型': 'json键是否存在', '期望结果': 'error', '是否通过': '通过'}]}, {'case_id': 'part_3_case_10', 'case_info': [{'测试用例编号': 'case_10', '是否执行': '是', '模块名称': 'part_3', '测试用例名称': '登录失败接口9_part_3', '测试用例步骤': 'step_01', '接口名称': '登录失败接口9_part_3', '请求方式': 'POST', '请求地址': '/api/login', '请求参数(get)': '{}', '提交数据(post)': '{"email": "763277"}', '取值方式': '无', '传值变量': '', '取值代码': '', '期望结果类型': 'json键是否存在', '期望结果': 'error', '是否通过': '通过'}]})
2025-09-23 20:19:25 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\test_runner\run_case.py:65" - get_test_suite - INFO - ['43bc9d6031']
2025-09-23 20:19:25 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\test_runner\run_case.py:108" - get_test_suite - INFO - 用例收集完成，共 16 个用例
2025-09-23 20:19:25 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\email_utils.py:48" - _load_and_validate_config - DEBUG - 加载邮件配置: 服务器=smtp.qq.com, 端口=465, 发件人=821745075@qq.com
2025-09-23 20:19:25 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\email_utils.py:66" - _validate_attachment_path - DEBUG - 验证附件路径成功: D:\workdir\DjangoProject3\api_test_platform\test_reports\接口自动化测试报告_20250923201905\接口自动化测试报告.html
2025-09-23 20:19:25 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\email_utils.py:23" - __init__ - INFO - 邮件工具初始化完成
2025-09-23 20:19:25 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\email_utils.py:113" - send_email - INFO - 第1/3次连接邮件服务器: smtp.qq.com:465
2025-09-23 20:19:26 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\email_utils.py:121" - send_email - INFO - 登录邮箱: 821745075@qq.com
2025-09-23 20:19:26 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\email_utils.py:136" - send_email - INFO - 准备发送邮件到: 821745075@qq.com, 2337125095@qq.com
2025-09-23 20:19:26 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\email_utils.py:80" - mail_message_body - DEBUG - 已添加邮件正文
2025-09-23 20:19:26 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\email_utils.py:96" - mail_message_body - DEBUG - 已添加附件: 接口自动化测试报告.html
2025-09-23 20:19:27 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\email_utils.py:142" - send_email - INFO - 邮件发送成功
2025-09-23 20:19:27 - ApitTest - "D:\workdir\DjangoProject3\api_test_platform\common\email_utils.py:166" - send_email - DEBUG - SMTP连接已关闭
